### ISSUE TITLE
simulation get input aspenfile fails to print correctly

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_client#12]
## TurbineLite returns matching aspenfile
Powershell
```
PS C:\Users\Administrator> Invoke-WebRequest -Uri http://localhost:8000/TurbineLite/Simulation/BFB_sinter_config_v6/inpu
t/aspenfile -OutFile aspenfile.acmf
PS C:\Users\Administrator> Invoke-WebRequest -Uri http://localhost:8000/TurbineLite/Simulation/BFB_sinter_config_v6/inpu
t/aspenfile -OutFile aspenfile2.acmf
PS C:\Users\Administrator>
PS C:\Users\Administrator>
PS C:\Users\Administrator> compare-object (get-content .\aspenfile.acmf ) (get-content .\aspenfile2.acmf )
PS C:\Users\Administrator> compare-object (get-content .\aspenfile.acmf ) (get-content C:\Users\Administrator\Desktop\FO
QUS\examples\Optimization\Model_Files\BFBv6.2.acmf)
PS C:\Users\Administrator>
```
## turbine_simulation_get 
Fails in the "_print" function, although it appears data was already decoded to latin-1
Set to content-type=text/plain, think this should be 'application/octet-stream'.  Currently implementation of "turbine.commands.decode_codec" uses 'latin-1' for both of these scenarios.  Think maybe this should be handled as binary..
```
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_get -r aspenfile -s
 BFB_sinter_config_v6 turbine.cfg
2019-04-24 22:41:17,063 - turbine.commands - DEBUG - Setup Logging Done
2019-04-24 22:41:17,079 - turbine.commands - DEBUG - passman "http://localhost:8000/TurbineLite/Simulation" password NOT
 registered
2019-04-24 22:41:17,079 - turbine.commands - DEBUG -
2019-04-24 22:41:17,079 - turbine.commands - DEBUG - {}
2019-04-24 22:41:17,079 - turbine.commands - DEBUG - retrieving job metadata: http://localhost:8000/TurbineLite/Simulati
on/BFB_sinter_config_v6/input/aspenfile?
2019-04-24 22:41:17,219 - turbine.commands - INFO - HTTP GET(200) OK: http://localhost:8000/TurbineLite/Simulation/BFB_s
inter_config_v6/input/aspenfile?
2019-04-24 22:41:17,329 - turbine.commands - DEBUG - Decode Content-Type: text/plain
Traceback (most recent call last):
  File "\ProgramData\Anaconda3\Scripts\turbine_simulation_get", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "C:\Users\Administrator\Desktop\turb_client\scripts\turbine_simulation_get", line 8, in <module>
    turbine_simulation_script.main_get()
  File "c:\users\administrator\desktop\turb_client\turbine\commands\turbine_simulation_script.py", line 181, in main_get

    func(data, out=out)
  File "c:\users\administrator\desktop\turb_client\turbine\commands\turbine_simulation_script.py", line 32, in _print_js
on
    print(data, end="", file=out)
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x92' in position 1694: character maps to <undefined>
```

**Comment by boverhof** [comment]
Powershell seems to save the files correctly, and they compare.
```
% Invoke-WebRequest -Uri http://localhost:8000/TurbineLite/Simulation/BFB_sinter_config_v6/input/configuration -Save file2
% compare-object (get-object file1) (get-object file2)
```

This python program works for some but not all file types.  
```
import urllib.request
with urllib.request.urlopen('http://localhost:8000/TurbineLite/Simulation/BFB_sinter_config_v6/input/configuration') as response:
   data = response.read()
   with open('test.txt', 'w', newline='\n') as out:
       print(data.decode('latin-1'), file=out)
```

There is a "decode" in turbine.commands that is called with Content-Type header, but doesn't seem to work in all instances.

**Comment by boverhof** [comment]
Think I fixed it by doing a .encode('latin-1') at the bottom of the _print_json function.  At least turbine_simulation_get is working now.
