### ISSUE TITLE
Update Base HTTP Library

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_client#19]
# Description
Some of the scripts were updated years ago ( simulation ), but appears some scripts were never updated and now fail with a new AWS API Gateway on SSL Version

Default all scripts to print out results as JSON, excepting grabbing files, etc.

## Application Scripts

- [x]  turbine_application_list

## Session Scripts
- [x]  turbine_session_result
- [x]  turbine_session_list
- [x] turbine_session_create
- [x] turbine_session_append
- [x] turbine_session_kill
- [x] turbine_session_status
- [x] turbine_session_stop
- [ ] turbine_session_delete

```
(py3.9) joshuas-mbp:foqus-deploy-cdk boverhof$ turbine_simulation_list ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg
Total Simulations: 3
	BFB_Flowsheet
	BFB_v11_FBS_01_26_2018
	bfb
(py3.9) joshuas-mbp:foqus-deploy-cdk boverhof$ 
(py3.9) joshuas-mbp:foqus-deploy-cdk boverhof$ 
(py3.9) joshuas-mbp:foqus-deploy-cdk boverhof$ turbine_session_list ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 186, in connect
    self.sock = ssl.wrap_socket(sock,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1406, in wrap_socket
    return context.wrap_socket(
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/bin/turbine_session_list", line 4, in <module>
    __import__('pkg_resources').run_script('TurbineClient==3.1.0', 'turbine_session_list')
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/EGG-INFO/scripts/turbine_session_list", line 14, in <module>
    turbine_session_script.main_list()
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/turbine_session_script.py", line 52, in main_list
    pages = get_paging(configFile, SECTION, options, **query)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 530, in get_paging
    return get_paging_by_url(url, configFile, section, query)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 507, in get_paging_by_url
    thisResults = _do_get(page_url)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 119, in _do_get
    result = _urlopen(url)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 111, in _urlopen
    result = urllib.request.urlopen(request)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/boverhof/Documents/workspace.ccsi2/py3.9/lib/python3.9/site-packages/TurbineClient-3.1.0-py3.9.egg/turbine/commands/__init__.py", line 199, in https_open
    return self.do_open(_HTTPSConnection, req)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)>
```

**Comment by boverhof** [comment]
`$ turbine_session_results --result=1 6f072126-3193-4c89-9af0-e835ac0fb0af  ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg | jq '.'`
```json
[
  {
    "Finished": "2022-08-17T23:49:51.090Z",
    "Input": {},
    "setup": "2022-08-17T23:49:47.533Z",
    "Reset": false,
    "TTL": 1660866591,
    "State": "success",
    "Create": "2022-08-17T23:43:05.533Z",
    "Type": "Job",
    "running": "2022-08-17T23:49:49.549Z",
    "Application": "fake-job",
    "Initialize": false,
    "User": "boverhof",
    "submit": "2022-08-17T23:49:45.985Z",
    "Id": "8d39408b-b7a2-4cfe-bcf7-e3e58a938fb8",
    "ConsumerId": "00000000-0000-0000-0000-000000000000",
    "Simulation": "fake-job",
    "Output": "[\"Lambda Fake Test Runner\"]",
    "Session": "6f072126-3193-4c89-9af0-e835ac0fb0af"
  },
  {
    "Finished": "2022-08-17T23:49:51.301Z",
    "Input": {},
    "setup": "2022-08-17T23:49:47.492Z",
    "Reset": false,
    "TTL": 1660866591,
    "State": "success",
    "Create": "2022-08-17T23:42:39.809Z",
    "Type": "Job",
    "running": "2022-08-17T23:49:49.774Z",
    "Application": "fake-job",
    "Initialize": false,
    "User": "boverhof",
    "submit": "2022-08-17T23:49:45.925Z",
    "Id": "ce7135da-087b-4a4b-96b7-6c32280021bc",
    "ConsumerId": "00000000-0000-0000-0000-000000000000",
    "Simulation": "fake-job",
    "Session": "6f072126-3193-4c89-9af0-e835ac0fb0af",
    "Message": "Processing Error: No Simulation Output"
  },
  {
    "Finished": "2022-08-17T23:49:51.472Z",
    "Input": {},
    "setup": "2022-08-17T23:49:47.532Z",
    "Reset": false,
    "TTL": 1660866591,
    "State": "success",
    "Create": "2022-08-17T23:43:12.230Z",
    "Type": "Job",
    "running": "2022-08-17T23:49:49.554Z",
    "Application": "fake-job",
    "Initialize": false,
    "User": "boverhof",
    "submit": "2022-08-17T23:49:45.983Z",
    "Id": "8e32970a-033e-4423-95a3-e4913a1a1fd6",
    "ConsumerId": "00000000-0000-0000-0000-000000000000",
    "Simulation": "fake-job",
    "Output": "[\"Lambda Fake Test Runner\"]",
    "Session": "6f072126-3193-4c89-9af0-e835ac0fb0af"
  }
]
```

**Comment by boverhof** [comment]
`$ turbine_session_list -j  ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg  | jq '.'`
```json
[
  "00827262-4ed3-48bc-addc-9fd7bad9655c",
  "04c86f31-7e00-437b-aec0-758ab828658a",
  "08c8e96d-56ee-48a4-b1aa-5472b7e96f58",
  "0bf89c2b-f7b0-4431-973d-09c6125187c4",
  "1dbad28e-4d84-4a96-a5b2-3d61acff71ea",
  "1eac7a3d-d6e3-4ed6-8fa1-a06c14cc0daf",
  "206ac73c-8b35-473e-819c-684a01a1c9a8",
  "209e6f2b-e2dd-4a46-b70f-062992489c10",
  "2c03fa03-20ad-4424-8408-9a7c1e15007d",
  "3ae200ae-1433-47a9-9cf8-3cc35688b676",
  "3afa209c-aa3e-46e2-a28a-104efbbaa9e1",
  "40c549a3-f866-441a-beff-9852eefc8d03",
  "450f860c-b4cc-45d8-81df-0cd03a74e926",
  "4b15665e-830d-4111-84c9-1537432b733e",
  "4cd7e8c1-4d0d-4f1a-bf3c-363b853531eb",
  "55406389-2940-41a6-a44c-a8166eea957e",
  "5a7444f9-0833-486b-8e05-9a5d777687dc",
  "5bb9406b-64f6-4948-ba36-a7c5227dd6b3",
  "5f415882-c994-4e8d-9411-511cdc8b0618",
  "66104f32-3e97-43eb-a97f-f23eacdac470",
  "6f072126-3193-4c89-9af0-e835ac0fb0af",
  "7009f7f9-235a-48a6-9807-86efe2398cb5",
  "70a25ca2-8d32-4019-8ca6-15192852612a",
  "717035ab-d8c4-41bf-b34b-26e5f51b0a96",
  "7171e6d7-f2ed-408d-a513-91fa5c130aaf",
  "72ed3e19-222f-4434-8ec7-0404c386d438",
  "795f1ccf-1422-4b45-ab37-4806780e4b0d",
  "871b8495-40eb-45ae-8f66-6355575dece4",
  "96b37d55-1541-48ab-82f1-818f16f7cfa1",
  "a3d20790-9557-451d-8533-6fd426d15538",
  "a4dbd3dd-da97-497e-a9f4-2ebe68374f77",
  "a7826210-0513-42d9-be27-31a83fd9bb99",
  "af4d2eb3-f438-45ca-bb7c-3e8efca3aaa5",
  "b997a318-a16b-4bb6-be78-d864973e5945",
  "becc7e4e-5173-497b-bcbf-2090e9ab7ea4",
  "cb0f5fd8-f16b-4b5f-b899-56dcb2d60870",
  "d0b92e94-4310-4f5a-b737-042f11770699",
  "d617c482-fdcf-4e4d-a4b5-7c94dbb67937",
  "dbd521e6-922a-4567-bf10-d07d6c6dd70d",
  "e00e941a-b345-4df3-8484-afc43d2efeb2",
  "e3a6040e-0499-42b5-b90c-00515b2c0b62",
  "f393c347-b948-4ea6-ac2a-9d9d8ce4393b",
  "f4263e17-937a-466a-84eb-81000cd24121",
  "fb0dbd9b-00a2-4a26-adc5-75a3bd3d4735",
  "ffe3ec95-19ca-4233-bf0e-1b0979698cb8"
]

```

**Comment by boverhof** [comment]
`$ turbine_session_create  ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg`
```
1b8e40c5-8f18-46e6-adc7-1f8533248e36
```

**Comment by boverhof** [comment]
`$ turbine_session_append 1b8e40c5-8f18-46e6-adc7-1f8533248e36 /tmp/fake-jobs.json ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg`
```json
["c6358eb0-bb70-4e18-8722-8820fdea8669"]
```

**Comment by boverhof** [comment]
`
$ turbine_session_status 1b8e40c5-8f18-46e6-adc7-1f8533248e36  ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg | jq '.'
`
```json
[
  {
    "Id": "6a148728-e03a-4e3a-9af1-adb0fc749650",
    "Application": "fake-job",
    "SessionId": "1b8e40c5-8f18-46e6-adc7-1f8533248e36",
    "Initialize": false,
    "Input": {},
    "State": "terminate",
    "Reset": false,
    "Simulation": "fake-job",
    "Create": "2022-08-18T19:30:39.810Z",
    "Finished": "2022-08-18T19:33:26.635Z"
  },
  {
    "Id": "c6358eb0-bb70-4e18-8722-8820fdea8669",
    "Application": "fake-job",
    "SessionId": "1b8e40c5-8f18-46e6-adc7-1f8533248e36",
    "Initialize": false,
    "Input": {},
    "State": "terminate",
    "Reset": false,
    "Simulation": "fake-job",
    "Create": "2022-08-18T19:32:14.469Z",
    "Finished": "2022-08-18T19:33:26.635Z"
  }
]
```

**Comment by boverhof** [comment]
```
$ turbine_session_stop  $SESSION ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg 
"478c6745-2fe0-4993-9ec4-428f93786669"
```

**Comment by boverhof** [comment]
`
$ turbine_application_list ~/Documents/workspace.ccsi2/foqus_working_dir_test/turbine_aws_west2.cfg | jq '.'
`
```json
[
  {
    "Name": "foqus",
    "Inputs": [
      "flowsheet"
    ]
  },
  {
    "Name": "AspenPlus",
    "Inputs": [
      "aspenfile"
    ]
  },
  {
    "Name": "ACM",
    "Inputs": [
      "aspenfile"
    ]
  }
]
```
